### PR TITLE
Store rapps catkin package information

### PR DESCRIPTION
**Pull request by esteve**
This branch adds the Catkin package information to every discovered Rapp.

Required by https://github.com/esteve/rocon_app_platform/tree/rocon_dependencies

### CODE REVIEW

**Comment by stonier** [comment]
Let me check this one first - going to have to update a few locations across the concert to avoid some breakages.

**Comment by stonier** [comment]
Just one place in https://github.com/robotics-in-concert/rocon_concert/blob/hydro-devel/concert_service_manager/src/concert_service_manager/service_pool.py#L140

Needs something like:

```
        cached_service_profile_information, unused_invalid_services = rocon_python_utils.ros.resource_index_from_package_exports(rocon_std_msgs.Strings.TAG_SERVICE)
        self._cached_service_profile_locations = {}
        for resource_name, (filename, unused_catkin_package) in cached_service_profile_information.iteritems():
            self._cached_service_profile_locations[resource_name] = filename
```

I am beginning to hate python tuples...they're so hard to introspect/autocomplete on what is actually inside.

**Comment by esteve** [comment]
@stonier I actually agree with you, I wanted to keep the API breakage to a minimum, but I'd rather use something else instead of a tuple. What do you think of adding a package field to the Rapp class that points to the catkin package?

**Comment by stonier** [comment]
Oh, github probably over-exaggurates my expression a little. I'm not as vehemently against them as all that, just a well developed dislike for them after having to adapt some code that decided to use them everywhere because they were so simple (no classes!). Works until your code starts getting so complex...

Here this is probably fine, but I can imagine having it inside the rapp could be useful (for computing dependency requirements...other?). If there isn't a pressing need for it and you have higher priority jobs though, the above is ok.

**Comment by stonier** [comment]
I'll let @bit-pirate handle the merge of this one when he does the other.

**Comment by stonier** [comment]
Pull request for concert_services coming shortly...

**Comment by stonier** [comment]
This is now in - we can refine this for our refined sensibilities later as needed.

**Pull request merged**
