### PR TITLE
A useful yaml library

### PR DESCRIPTION
**Pull request by stonier**
This is awesome - it lets us include yamls from other yamls and also merge yamls together.

### CODE REVIEW

**Comment by bit-pirate** [comment]
This comes from where?

**Comment by stonier** [comment]
Links and notes in the sphinx docs (last commit).

**Comment by stonier** [comment]
Going in...this is required for the urdf customisations we are doing on gopher. 

Just some extra notes: 

I didn't use the library here - yaml doesn't actually merge very well. I also tried `anyconfig` (we have a deb on our yujin server now) which is a nicer library with more merging options, however there is a  key problem with merging.

Lists in yaml prevent intelligent merging. how does a snippet from a list know to which list element it belongs so that it can do the appropriate override? Things need to be keyed, so if your yaml is structured as dictionaries only, then you are ok. Or if you do have lists, but unique ids for each element in the list, then you can write your own custom merger.

It aint a perfect world :/

**Comment by stonier** [comment]
This library does have useful ideas for inheritence and composition though - might recycle those in some form in the future.

**Pull request merged**
