### PR TITLE
Update rules.yaml

### PR DESCRIPTION
**Pull request by ChienDavid**
Dear maintainers,
Hello, my name is Chien. I am a beginner in rocon.
I would like to use a new robot named Robotis_OP1 in rocon.
Please help me make Robotis_OP1 official.
Thank you very much.
-Chien-

### CODE REVIEW

**Comment by jihoonl** [comment]
Thanks. Can you make OP lowercase? e.g) robotis_op1

**Comment by ChienDavid** [comment]
Oh what do you mean by "make OP lowercase"?

**Comment by jihoonl** [comment]
I meant `robotis_OP1`  -> `robotis_op1`

**Comment by ChienDavid** [comment]
Ah, sure, I will correct it.
Thank you.

**Comment by stonier** [comment]
Added in 7790331e (devel) and 6cb8f9c8 (indigo) and 2049e3a4 (gopher)

**Pull request closed without merging**
